fixing the combatibility issue
CS3250Team3/MavenCS3250Team3 pull request #44
Opened 2021-04-20 19:15 UTC by James-R-Marshall

2021-04-23 01:44 UTC, Kyle-Brown-edu approved these changes
Still has merge conflicts

2021-04-23 01:48 UTC, Wolfy319 requested changes
Could you remove anything that is in the target/ file? It looks like a lot of this stuff is local files and compiled stuff that we don't want

2021-04-28 00:00 UTC, Wolfy319 submitted a review, later dismissed

2021-05-04 01:09 UTC, Wolfy319 approved these changes

2021-05-04 01:10 UTC, merged